In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv("./data/소상공인시장진흥공단_상가(상권)정보_경기_202409.csv")
data.head()

C:\Users\5-11\AppData\Local\Temp\ipykernel_14008\3200924126.py:1: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  data = pd.read_csv("./data/소상공인시장진흥공단_상가(상권)정보_경기_202409.csv")

,상가업소번호,상호명,지점명,상권업종대분류코드,상권업종대분류명,상권업종중분류코드,상권업종중분류명,상권업종소분류코드,상권업종소분류명,표준산업분류코드,...,건물관리번호,건물명,도로명주소,구우편번호,신우편번호,동정보,층정보,호정보,경도,위도
0,MA0101202210A0071854,희야,NaN,I2,음식,I203,일식,I20301,일식 회/초밥,I56122,...,4122010100108160002005525,NaN,경기도 평택시 특구로23번길 19,459813.0,17774,NaN,1,NaN,127.062091,37.067553
1,MA0101202210A0076234,비에이치씨충호회관점,NaN,I2,음식,I210,기타 간이,I21006,치킨,I56193,...,4136025024203190001025405,NaN,경기도 남양주시 와부읍 석실로260번길 74-17,472905.0,12203,NaN,1,NaN,127.225686,37.602928
2,MA0101202210A0058768,생곡메밀막국수,NaN,I2,음식,I201,한식,I20105,국수/칼국수,I56112,...,4159011700102080000000001,NaN,경기도 화성시 동탄지성로 222,445360.0,18421,NaN,1,NaN,127.053118,37.213831
3,MA010120220805430777,고매커피,NaN,I2,음식,I212,비알코올,I21201,카페,I56221,...,4146310800102450002019118,NaN,경기도 용인시 기흥구 원고매로2번길 85-2,446901.0,17086,NaN,1,NaN,127.110760,37.219495
4,MA010120220805430785,꿈의부동산공인중개사사무소,NaN,L1,부동산,L102,부동산 서비스,L10203,부동산 중개/대리업,L68221,...,4127110400108660017023856,NaN,경기도 안산시 상록구 본원로 49,426813.0,15551,NaN,NaN,NaN,126.864005,37.292049

In [4]:
data.columns

Index(['상가업소번호', '상호명', '지점명', '상권업종대분류코드', '상권업종대분류명', '상권업종중분류코드',
       '상권업종중분류명', '상권업종소분류코드', '상권업종소분류명', '표준산업분류코드', '표준산업분류명', '시도코드',
       '시도명', '시군구코드', '시군구명', '행정동코드', '행정동명', '법정동코드', '법정동명', '지번코드',
       '대지구분코드', '대지구분명', '지번본번지', '지번부번지', '지번주소', '도로명코드', '도로명', '건물본번지',
       '건물부번지', '건물관리번호', '건물명', '도로명주소', '구우편번호', '신우편번호', '동정보', '층정보',
       '호정보', '경도', '위도'],
      dtype='object')

In [5]:
data_gyeonggi = data[(data["상권업종대분류코드"] == "I2") & (data["시도코드"].astype(str).str.startswith("41"))]

### 컬럼 선택

In [8]:
columns = [
    "상가업소번호", "상호명", "지점명", "상권업종대분류코드", "상권업종대분류명",
    "상권업종중분류코드", "상권업종중분류명", "상권업종소분류코드", "상권업종소분류명",
    "표준산업분류코드", "표준산업분류명", "시도코드", "시도명", "시군구코드",
    "시군구명", "행정동코드", "행정동명", "도로명코드", "도로명", "도로명주소",
    "경도", "위도"]

In [9]:
data_gyeonggi = data_gyeonggi[columns]

In [11]:
data_gyeonggi.to_csv('data_gyeonggi.csv', index=False, encoding='utf-8-sig')

### ---------------------------------------------------------전처리 시작--------------------------------------------------------------------

In [2]:
data = pd.read_csv("./data/data_gyeonggi.csv")
data.head()

C:\Users\5-11\AppData\Local\Temp\ipykernel_14160\2228071279.py:1: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  data = pd.read_csv("./data/data_gyeonggi.csv")

,상가업소번호,상호명,지점명,상권업종대분류코드,상권업종대분류명,상권업종중분류코드,상권업종중분류명,상권업종소분류코드,상권업종소분류명,표준산업분류코드,...,시도명,시군구코드,시군구명,행정동코드,행정동명,도로명코드,도로명,도로명주소,경도,위도
0,MA0101202210A0071854,희야,NaN,I2,음식,I203,일식,I20301,일식 회/초밥,I56122,...,경기도,41220,평택시,41220520,서정동,4.122044e+11,경기도 평택시 특구로23번길,경기도 평택시 특구로23번길 19,127.062091,37.067553
1,MA0101202210A0076234,비에이치씨충호회관점,NaN,I2,음식,I210,기타 간이,I21006,치킨,I56193,...,경기도,41360,남양주시,41360250,와부읍,4.136044e+11,경기도 남양주시 와부읍 석실로260번길,경기도 남양주시 와부읍 석실로260번길 74-17,127.225686,37.602928
2,MA0101202210A0058768,생곡메밀막국수,NaN,I2,음식,I201,한식,I20105,국수/칼국수,I56112,...,경기도,41590,화성시,41590540,병점2동,4.159032e+11,경기도 화성시 동탄지성로,경기도 화성시 동탄지성로 222,127.053118,37.213831
3,MA010120220805430777,고매커피,NaN,I2,음식,I212,비알코올,I21201,카페,I56221,...,경기도,41463,용인시 기흥구,41463540,기흥동,4.146344e+11,경기도 용인시 기흥구 원고매로2번길,경기도 용인시 기흥구 원고매로2번길 85-2,127.110760,37.219495
4,MA010120220805430792,푸라닭성남동점,NaN,I2,음식,I210,기타 간이,I21006,치킨,I56193,...,경기도,41133,성남시 중원구,41133510,성남동,4.113332e+11,경기도 성남시 중원구 광명로,경기도 성남시 중원구 광명로 138,127.143503,37.437268

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 167161 entries, 0 to 167160
Data columns (total 22 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   상가업소번호     167161 non-null  object
 1   상호명        167161 non-null  object
 2   지점명        9032 non-null    object
 3   상권업종대분류코드  167161 non-null  object
 4   상권업종대분류명   167161 non-null  object
 5   상권업종중분류코드  167161 non-null  object
 6   상권업종중분류명   167161 non-null  object
 7   상권업종소분류코드  167161 non-null  object
 8   상권업종소분류명   167161 non-null  object
 9   표준산업분류코드   167099 non-null  object
 10  표준산업분류명    167099 non-null  object
 11  시도코드       167161 non-null  int64
 12  시도명        167161 non-null  object
 13  시군구코드      167161 non-null  int64
 14  시군구명       167161 non-null  object
 15  행정동코드      167161 non-null  int64
 16  행정동명       167161 non-null  object
 17  도로명코드      167067 non-null  float64
 18  도로명        167161 non-null  object
 19  도로명주소      167161 non-null  object
 20  경도         167161 non-null  float64
 21  위도         167161 non-null  float64
dtypes: float64(3), int64(3), object(16)
memory usage: 28.1+ MB